# Generated by Django 4.2.6 on 2023-10-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluevoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='bluevoice.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='bluevoice.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='bluevoice.cartitem'),
        ),
    ]
