# Generated by Django 4.2.6 on 2023-10-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluevoice', '0003_remove_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
